export const PLANETS = [
  {
    name: "Mercury",
    radius: 5.8,
    speed: 0.8,
    size: 0.38,
    color: "#b1b1b1",
    texture: "/mercury.png",
    bumpMap: "/mercury_bump.jpg",
  },
  {
    name: "Venus",
    radius: 10.8,
    speed: 0.6,
    size: 0.95,
    color: "#e3c16f",
    texture: "/venus.webp",
    bumpMap: "/venus_bump.jpeg",
  },
  {
    name: "Earth",
    radius: 115,
    speed: 0.5,
    size: 1,
    color: "#4a90e2",
    texture: "/earth.jpg",
    bumpMap: "/earth_bump.jpeg",
  },
  {
    name: "Mars",
    radius: 122.7,
    speed: 0.4,
    size: 0.53,
    color: "#c1440e",
    texture: "/mars.jpg",
    bumpMap: "/mars_bump.jpg",
  },
  {
    name: "Jupiter",
    radius: 177.8,
    speed: 0.2,
    size: 11.2,
    color: "#e6c07b",
    texture: "/jupiter.jpg",
    bumpMap: "/jupiter_bump.jpg",
  },
  {
    name: "Saturn",
    radius: 142.7,
    speed: 0.1,
    size: 9.45,
    color: "#d8c47a",
    texture: "/saturn.jpg",
    bumpMap: "/saturn_bump.jpeg",
  },
  {
    name: "Uranus",
    radius: 287.1,
    speed: 0.07,
    size: 4.01,
    color: "#94e0e9",
    texture: "/uranus.jpg",
    bumpMap: "/uranus_bump.jpg",
  },
  {
    name: "Neptune",
    radius: 449.5,
    speed: 0.05,
    size: 3.88,
    color: "#4059ad",
    texture: "/neptune.jpg",
    bumpMap: "/neptune_bump.jpeg",
  },
];
