import type { Metadata } from "next";
import "./globals.css";
import { YearGlobe } from "@/components/YearWheel";

import { BodyWrapper } from "./root-styling";
import { cookies } from "next/headers"; 
import SplashScreenProvider from "@/components/SplashScreenProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const introCookie = (await cookies()).get("intro-shown")?.value === "true";

  return (
    <BodyWrapper>
      <SplashScreenProvider>
        <div style={{ position: "fixed", inset: 0, zIndex: -1 }}>
          <YearGlobe />
        </div>
        <div id="globe-overlay" style={{}} />
        {children}
      </SplashScreenProvider>
    </BodyWrapper>
  );
}
